'use client'

import React, { useState } from 'react'
import { ProjectReport, ReportAudience } from '@/types'
import ReportProseViewer from './ReportProseViewer'
import {
  Copy,
  Check,
  Download,
  FileText,
  Users,
  Code,
  Sparkles,
  TrendingUp,
  Percent,
} from 'lucide-react'
import { toast } from '@/lib/toast'

interface ReportCardProps {
  report: ProjectReport
  activeAudience: ReportAudience
}

export default function ReportCard({ report, activeAudience }: ReportCardProps) {
  const [copied, setCopied] = useState(false)
  const [isExporting, setIsExporting] = useState(false)

  const isTechnical = activeAudience === 'technical'
  const activeProse = isTechnical
    ? report.technical_version_text
    : report.stakeholder_version_text

  // Copy report prose to clipboard
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(activeProse)
      setCopied(true)
      toast.success('Report copied to clipboard', 'Copied')
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback
      setCopied(true)
      toast.success('Report copied to clipboard', 'Copied')
      setTimeout(() => setCopied(false), 2000)
    }
  }

  // Export report as PDF (via print-friendly document trigger)
  const handleDownloadPDF = () => {
    setIsExporting(true)
    const title = `${report.title || 'ProjectPilot AI Report'} - ${
      isTechnical ? 'Technical' : 'Stakeholder'
    } (${report.label || report.week_start})`

    const printWindow = window.open('', '_blank')
    if (!printWindow) {
      setIsExporting(false)
      return
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title}</title>
          <meta charset="utf-8" />
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
              color: #0F172A;
              background: #FFFFFF;
              padding: 40px;
              line-height: 1.7;
              max-width: 800px;
              margin: 0 auto;
            }
            .header {
              border-bottom: 2px solid #E2E8F0;
              padding-bottom: 20px;
              margin-bottom: 30px;
            }
            .brand {
              color: #1F3864;
              font-size: 20px;
              font-weight: bold;
              margin-bottom: 4px;
            }
            .title {
              font-size: 22px;
              font-weight: bold;
              color: #0F172A;
              margin-top: 12px;
            }
            .meta {
              font-size: 12px;
              color: #64748B;
              margin-top: 4px;
            }
            .badge {
              display: inline-block;
              background: #EEF2FF;
              color: #4F46E5;
              border: 1px solid #C7D2FE;
              font-size: 11px;
              font-weight: bold;
              padding: 3px 10px;
              border-radius: 9999px;
              margin-top: 8px;
            }
            h3 {
              font-size: 16px;
              color: #1F3864;
              margin-top: 24px;
              margin-bottom: 8px;
              border-bottom: 1px solid #E2E8F0;
              padding-bottom: 4px;
            }
            p {
              margin: 8px 0;
              font-size: 13.5px;
              color: #334155;
            }
            .footer {
              margin-top: 40px;
              padding-top: 15px;
              border-top: 1px solid #E2E8F0;
              font-size: 11px;
              color: #94A3B8;
              text-align: right;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="brand">ProjectPilot AI &bull; Audience-Aware Auto Report</div>
            <div class="title">${report.title || 'Weekly Engineering Report'}</div>
            <div class="meta">${report.label || report.week_start} &bull; ${report.sprint_name || 'Sprint'}</div>
            <div class="badge">Audience: ${
              isTechnical ? 'Technical Teams & Engineering Leads' : 'Executive Stakeholders & Product Owners'
            }</div>
          </div>
          <div class="content">
            ${activeProse
              .split('\n\n')
              .map((block) => {
                if (block.startsWith('###')) {
                  return `<h3>${block.replace(/^###\s*/, '')}</h3>`
                }
                return `<p>${block.replace(/\n/g, '<br/>')}</p>`
              })
              .join('')}
          </div>
          <div class="footer">
            Generated by ProjectPilot AI &bull; Confidential &bull; ${new Date().toLocaleDateString()}
          </div>
        </body>
      </html>
    `

    printWindow.document.open()
    printWindow.document.write(htmlContent)
    printWindow.document.close()
    setIsExporting(false)
    toast.success('Report downloaded as PDF', 'Export Complete')

    // Trigger PDF Print Dialog after document finishes rendering
    setTimeout(() => {
      printWindow.focus()
      printWindow.print()
    }, 250)
  }

  return (
    <div className="bg-white/95 backdrop-blur-sm rounded-2xl border border-[#E2E8F0] p-7 sm:p-9 shadow-[0_4px_25px_-4px_rgba(15,23,42,0.05)] space-y-6">
      {/* Top Header Row */}
      <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 pb-6 border-b border-[#E2E8F0]">
        <div className="space-y-1.5">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-xl bg-indigo-50 text-[#4F46E5] flex items-center justify-center border border-indigo-100">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-[19px] font-bold text-[#0F172A] tracking-tight">
                {report.title || 'Sprint Report'}
              </h2>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-2.5 text-[12px] text-[#64748B] pt-0.5">
            <span className="font-semibold text-[#0F172A] bg-slate-50 px-2.5 py-0.5 rounded-md border border-slate-200/80">
              {report.label || report.week_start}
            </span>
            <span>&bull;</span>
            <span>{report.sprint_name || 'Active Sprint'}</span>
            <span>&bull;</span>

            {/* Audience Badge */}
            <span
              className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[11px] font-bold shadow-xs ${
                isTechnical
                  ? 'bg-indigo-50 text-[#4F46E5] border border-indigo-200/70'
                  : 'bg-emerald-50 text-[#16A34A] border border-emerald-200/70'
              }`}
            >
              {isTechnical ? (
                <>
                  <Code className="w-3 h-3" />
                  <span>Audience: Engineering Leads &amp; Devs</span>
                </>
              ) : (
                <>
                  <Users className="w-3 h-3" />
                  <span>Audience: Product &amp; Stakeholders</span>
                </>
              )}
            </span>
          </div>
        </div>

        {/* Action Buttons: Copy to Clipboard & Download as PDF */}
        <div className="flex items-center gap-2.5 self-start sm:self-auto">
          <button
            type="button"
            onClick={handleCopy}
            className="inline-flex items-center gap-1.5 text-[12px] font-semibold text-[#64748B] hover:text-[#0F172A] bg-slate-50 hover:bg-slate-100 border border-[#E2E8F0] px-3.5 py-2 rounded-xl transition-all shadow-xs cursor-pointer"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-600" />
                <span className="text-emerald-700 font-bold">Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy to Clipboard</span>
              </>
            )}
          </button>

          <button
            type="button"
            onClick={handleDownloadPDF}
            disabled={isExporting}
            className="inline-flex items-center gap-1.5 text-[12px] font-semibold text-white bg-[#4F46E5] hover:bg-[#4338CA] px-4 py-2 rounded-xl transition-all shadow-sm shadow-indigo-500/20 cursor-pointer disabled:opacity-60"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download as PDF</span>
          </button>
        </div>
      </div>

      {/* Metric Quick Stats Banner if available */}
      {report.key_metrics && (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50/70 p-3.5 rounded-xl border border-[#E2E8F0]/80 text-[12px]">
          <div className="flex items-center gap-2">
            <Percent className="w-4 h-4 text-[#4F46E5] shrink-0" />
            <div>
              <span className="text-[#64748B] text-[11px] block">Velocity Completion</span>
              <span className="font-bold text-[#0F172A]">
                {report.key_metrics.velocity_completion}%
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <TrendingUp className="w-4 h-4 text-[#16A34A] shrink-0" />
            <div>
              <span className="text-[#64748B] text-[11px] block">On-Time Probability</span>
              <span className="font-bold text-[#16A34A]">
                {report.key_metrics.on_time_probability}%
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-[#D97706] shrink-0" />
            <div>
              <span className="text-[#64748B] text-[11px] block">Risk Radar</span>
              <span className="font-bold text-[#D97706]">
                {report.key_metrics.high_risk_tickets_count} Flagged
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <FileText className="w-4 h-4 text-indigo-600 shrink-0" />
            <div>
              <span className="text-[#64748B] text-[11px] block">Merged Pull Requests</span>
              <span className="font-bold text-[#0F172A]">
                {report.key_metrics.prs_merged_count} PRs
              </span>
            </div>
          </div>
        </div>
      )}

      {/* Main Prose Viewer */}
      <div className="pt-2">
        <ReportProseViewer proseText={activeProse} />
      </div>
    </div>
  )
}
